language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database strata_test' -U postgres
  - psql -c "create role strata with password 'strata@' login createdb superuser" -U postgres
before_install:
  - gem install bundler
